version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - pipenv
  - pyproject
  - pytest
  - stackoverflow
  - venv
  - virtualenv
  - virtualenvwrapper
ignoreWords: []
import: []
