version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Anson
  - bierner
  - Carberra
  - figclass
  - lextudio
  - linenos
  - literalinclude
  - maxdepth
  - mushan
  - packagename
  - pipenv
  - projectname
  - pyenv
  - pyproject
  - pypy
  - pytest
  - pyvenv
  - quickstart
  - realpython
  - setuptools
  - stackoverflow
  - toctree
  - venv
  - virtualenv
  - virtualenvwrapper
  - Wildenstein
  - yzhang
ignoreWords: []
import: []
