version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Anson
  - bierner
  - Carberra
  - lextudio
  - mushan
  - packagename
  - pipenv
  - pyenv
  - pyproject
  - pypy
  - pytest
  - pyvenv
  - quickstart
  - setuptools
  - stackoverflow
  - venv
  - virtualenv
  - virtualenvwrapper
  - yzhang
ignoreWords: []
import: []
