version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Anson
  - autoattribute
  - autoclass
  - autodecorator
  - autodoc
  - autofunction
  - automethod
  - automodule
  - bierner
  - blogpost
  - bysource
  - Calderone's
  - Carberra
  - Docstrings
  - figclass
  - groupwise
  - lextudio
  - linenos
  - literalinclude
  - maxdepth
  - mushan
  - packagename
  - pipenv
  - pydoc
  - pyenv
  - pyproject
  - pypy
  - pytest
  - pyvenv
  - quickstart
  - realpython
  - setuptools
  - stackoverflow
  - toctree
  - undoc
  - venv
  - viewcode
  - virtualenv
  - virtualenvwrapper
  - Wildenstein
  - yzhang
ignoreWords: []
import: []
