# This file is used to build the sphinx documentation and push it to the gh-pages branch of the repository
# Adapted from the YouTube tutorial video [GitHub Action: Sphinx documentation](https://www.youtube.com/watch?v=SxkM1SK9YlI) by EEHolmes-DataScience

on:
  push:
    branches: [main]

jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      # Checkout the GitHub repository into the virual machine
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install python on the virtual machine
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      # Pip install sphinx and sphinx-rtd-theme
      - name: Install dependencies
        run: |
            python -m pip install -U sphinx
            python -m pip install sphinx-rtd-theme

      # Execute the source code's makefile to build the sphinx docs
      - name: Build sphinx docs
        run: |
              make -C docs clean
              make -C docs html

      # Grab the generated html files from the build folder and commit them to the gh-pages branch
      - name: Init new repo in dist folder and commit generated files
        run: |
          cd docs/_build/html/
          git init
          touch .nojekyll
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'

      # Use an action to simplify the force push to the gh-pages branch
      - name: Force push to destination branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs/build/html


